from __future__ import annotations

from datetime import datetime
from typing import Protocol

from quanterback.domain.persisted import (
    PersistedBacktest,
    PersistedDecision,
    PersistedNotification,
    PersistedOrder,
    PersistedPosition,
    PersistedTrade,
    PersistedUserTrigger,
    ScanRun,
)
from quanterback.domain.position import OpenLifecycle


class StateStore(Protocol):
    """Repository pattern. Raw SQL inside adapters; no ORM."""

    def insert_scan_run(self, run: ScanRun) -> int: ...
    def update_scan_run(self, run: ScanRun) -> None: ...
    def insert_decision(self, decision: PersistedDecision) -> int: ...
    def insert_backtest(self, report: PersistedBacktest) -> int: ...
    def insert_order(self, order: PersistedOrder) -> int: ...
    def upsert_position(self, position: PersistedPosition) -> int: ...
    def insert_notification(self, n: PersistedNotification) -> int: ...
    def update_notification(self, n: PersistedNotification) -> None: ...
    def insert_user_trigger(self, t: PersistedUserTrigger) -> int: ...
    def query_pending_user_triggers(self) -> list[PersistedUserTrigger]: ...
    def mark_user_trigger_processed(self, trigger_id: int) -> None: ...
    def query_open_lifecycles(self) -> list[OpenLifecycle]: ...
    def query_recent_decisions(self, ticker: str, limit: int) -> list[PersistedDecision]: ...
    def query_pending_notifications(self) -> list[PersistedNotification]: ...
    def insert_trade(self, trade: PersistedTrade) -> int: ...
    def trade_exists_for_order(self, order_id: str) -> bool: ...
    def list_recent_trades(self, limit: int = 20) -> list[PersistedTrade]: ...
    def get_open_positions(self) -> list[PersistedPosition]: ...
    def mark_position_closed(
        self, ticker: str, closed_at: datetime, exit_price: float
    ) -> None: ...
